spring:
  thymeleaf:
    mode: HTML5
  datasource:
    url: jdbc:mysql://localhost:3306/whlg01?serverTimezone=Asia/Shanghai&characterEnconding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8090
logging:
  level:
    root: info
  file:
    path: log/blog